development:
  btc_master_private_key: tprv8ZgxMBicQKsPd9iCBBYQmy2YCcF947HfRNXJPkBdnS5NpeGVkJDCkfkRKTDWSJeE8BcYcRzkiLScpMok3pGH9izLQXgKFbWXinqG9YJdxdh
  top_up_receiving_wallet_pk: lSjzPkrAfgjuxhccc7So6filfFIF6xOS
  gwx_distribution_wallet: TCJO4YDSI5IOJYLIJK5N5D6KFCRZA4LIMGKM65UY
  gwx_distribution_wallet_pk: c9a0edf4a4e0e54e2a72ca90680ddd9d82805f64ba8d462523fe7319d6205487

test:
  btc_master_private_key: tprv8ZgxMBicQKsPdxZrHR1ZacxvmmxfMe3BVvgFKFHjiYkG4EP1aAH44sQVVuwyzM6CdWgw5N8kY7uHrTbxEgQ9xq2tuwk7YRTsCPZ95grmxgp
  top_up_receiving_wallet_pk: UZC28wH4Q18xhXHlQHh7UwaDzrVOAj3X
  gwx_distribution_wallet: TDHIKM6IRFHFA7FBZISTZFCMJMMBJI3M4CCA4VO2
  gwx_distribution_wallet_pk: 53ecd213b4e6d6631efaa3873643df686d99b88bbdbc2c1076296e10c36c7a77

staging:
  btc_master_private_key: tprv8ZgxMBicQKsPf28ydAVh8ty4rbda272YFzGfmWwHufNaqDKTHJ8gSyKQMJ5E5fzqBVixXh7QZZXu7PfYdJoWi9gW5oWubBx2fSaFyZhN2YQ
  top_up_receiving_wallet_pk: 5r7S9qofe6v5NvzpUu7kzoXKMRd2sz7N
  gwx_distribution_wallet: 505775d2525df6cfcadd4770736cea14b7d1226ccaf10d285dc54638617aa782
  gwx_distribution_wallet_pk: TCXBLKALO5OGMGSXWMGKNG3LAF7PEOB5YUTW22M7

production:
  btc_master_private_key:
  top_up_receiving_wallet_pk: Wm65EDXKWRI96eoVzfgWGm6ZMTLyiEEn
  gwx_distribution_wallet: 
  gwx_distribution_wallet_pk:

