development:
  btc_master_private_key: tprv8ZgxMBicQKsPd9iCBBYQmy2YCcF947HfRNXJPkBdnS5NpeGVkJDCkfkRKTDWSJeE8BcYcRzkiLScpMok3pGH9izLQXgKFbWXinqG9YJdxdh
  top_up_receiving_wallet_pk: lSjzPkrAfgjuxhccc7So6filfFIF6xOS

test:
  btc_master_private_key: tprv8ZgxMBicQKsPdxZrHR1ZacxvmmxfMe3BVvgFKFHjiYkG4EP1aAH44sQVVuwyzM6CdWgw5N8kY7uHrTbxEgQ9xq2tuwk7YRTsCPZ95grmxgp
  top_up_receiving_wallet_pk: UZC28wH4Q18xhXHlQHh7UwaDzrVOAj3X

staging:
  btc_master_private_key: tprv8ZgxMBicQKsPf28ydAVh8ty4rbda272YFzGfmWwHufNaqDKTHJ8gSyKQMJ5E5fzqBVixXh7QZZXu7PfYdJoWi9gW5oWubBx2fSaFyZhN2YQ
  top_up_receiving_wallet_pk: 5r7S9qofe6v5NvzpUu7kzoXKMRd2sz7N

production:
  btc_master_private_key:
  top_up_receiving_wallet_pk: Wm65EDXKWRI96eoVzfgWGm6ZMTLyiEEn
