development:
  btc_master_private_key: tprv8ZgxMBicQKsPd9iCBBYQmy2YCcF947HfRNXJPkBdnS5NpeGVkJDCkfkRKTDWSJeE8BcYcRzkiLScpMok3pGH9izLQXgKFbWXinqG9YJdxdh

test:
  btc_master_private_key: tprv8ZgxMBicQKsPdxZrHR1ZacxvmmxfMe3BVvgFKFHjiYkG4EP1aAH44sQVVuwyzM6CdWgw5N8kY7uHrTbxEgQ9xq2tuwk7YRTsCPZ95grmxgp

staging:
  btc_master_private_key: tprv8ZgxMBicQKsPf28ydAVh8ty4rbda272YFzGfmWwHufNaqDKTHJ8gSyKQMJ5E5fzqBVixXh7QZZXu7PfYdJoWi9gW5oWubBx2fSaFyZhN2YQ

production:
  btc_master_private_key: